//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameViewGraph.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrameViewGraph.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string EN_AppSettings_Language {
            get {
                return ResourceManager.GetString("EN_AppSettings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file....
        /// </summary>
        internal static string EN_File_OpenFile {
            get {
                return ResourceManager.GetString("EN_File_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string EN_Language_EN {
            get {
                return ResourceManager.GetString("EN_Language_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string EN_Language_RU {
            get {
                return ResourceManager.GetString("EN_Language_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string EN_Menu_About {
            get {
                return ResourceManager.GetString("EN_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App settings.
        /// </summary>
        internal static string EN_Menu_AppSettings {
            get {
                return ResourceManager.GetString("EN_Menu_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string EN_Menu_File {
            get {
                return ResourceManager.GetString("EN_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph.
        /// </summary>
        internal static string EN_Menu_Graph {
            get {
                return ResourceManager.GetString("EN_Menu_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph settings.
        /// </summary>
        internal static string EN_Menu_GraphSettings {
            get {
                return ResourceManager.GetString("EN_Menu_GraphSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph type.
        /// </summary>
        internal static string EN_Menu_GraphType {
            get {
                return ResourceManager.GetString("EN_Menu_GraphType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string RU_AppSettings_Language {
            get {
                return ResourceManager.GetString("RU_AppSettings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть файл....
        /// </summary>
        internal static string RU_File_OpenFile {
            get {
                return ResourceManager.GetString("RU_File_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string RU_Language_EN {
            get {
                return ResourceManager.GetString("RU_Language_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string RU_Language_RU {
            get {
                return ResourceManager.GetString("RU_Language_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string RU_Menu_About {
            get {
                return ResourceManager.GetString("RU_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки программы.
        /// </summary>
        internal static string RU_Menu_AppSettings {
            get {
                return ResourceManager.GetString("RU_Menu_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        internal static string RU_Menu_File {
            get {
                return ResourceManager.GetString("RU_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График.
        /// </summary>
        internal static string RU_Menu_Graph {
            get {
                return ResourceManager.GetString("RU_Menu_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки графика.
        /// </summary>
        internal static string RU_Menu_GraphSettings {
            get {
                return ResourceManager.GetString("RU_Menu_GraphSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип графика.
        /// </summary>
        internal static string RU_Menu_GraphType {
            get {
                return ResourceManager.GetString("RU_Menu_GraphType", resourceCulture);
            }
        }
    }
}
